// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qscrcavbolvqizyevmso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzY3JjYXZib2x2cWl6eWV2bXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTQ5ODEsImV4cCI6MjA1Nzk3MDk4MX0.0IYCwAWiPoQ17r4vkqc29KTrQ4LG8KX3E2mbLiOnZEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);